src/rails/config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :expts,:collection => { :compare => :put }

  

  map.root :controller => "expts"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

src/rails/app/models/expt.rb
require 'fenxi'
class Expt < Fenxi::FenxiDatabase

  def to_param
    @path.gsub(/[\/\.]/,'_').downcase
  end
end

src/rails/app/models/user_session.rb
class UserSession
  def initialize(session)
    @store = session
    @store[:expts] ||= []
    @store[:compare] ||= []
  end

  def save(tag, value)
    @store[tag] << value
  end

  def find(tag, param)
    @store[tag].detect { |l| l.to_param == param } || raise("#{param} not found")
  end

  def get(tag)
    @store[tag]
  end
  
  def save_expt(expt)
    save(:expts, expt)
  end

  def find_expt(param)
    find(:expts, param)
  end
  
  def loaded?(param)
    @store[:expts].detect { |l| l.to_param == param }
  end
  
  def delete_expt(param)
    @store[:expts].delete_if { |l| l.to_param == param }
  end
  
  def get_expts
    get(:expts)
  end

  def get_compare
    get(:compare)
  end

  def save_compare(comp)
    save(:compare, comp)
  end

  def find_compare(param)
    find(:compare, param)
  end

  def num_expts
    @store[:expts].length
  end
end

src/rails/app/controllers/application.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  self.allow_forgery_protection = false
  helper :all # include all helpers, all the time

  # See ActionController::RequestForgeryProtection for details
  # Uncomment the :secret if you're not using the cookie session store
  protect_from_forgery  :secret => 'ebb82f417645ada233a854216bb5cd14'
  
  private
  def user_session
    @user_session ||= UserSession.new(session)
  end
  helper_method :user_session
  # See ActionController::Base for details 
  # Uncomment this to filter the contents of submitted sensitive data parameters
  # from your application log (in this case, all fields with names like "password"). 
  # filter_parameter_logging :password
end

src/rails/app/controllers/expts_controller.rb
class ExptsController < ApplicationController
  before_filter :get_expt, :except => [:index, :new, :new_from_compare, :create, :las, :lac]
  around_filter :respond_catch_exception_rjs, :only => [:create, :new_from_compare, :show_section, :custom_query]
  # GET /expts
  def index
    @expts = user_session.get_expts
  end

  # GET /expts/1
  def show
    @tool = params[:tool]
    if @tool.nil? then
      @tool = default_tool_for(@expt)
    elsif !@expt.tools.keys.find {|t| t == @tool}
      flash[:error] = "Could not find tool #{@tool.inspect}"
    end
    @expt.execute_sections_for_tool(@tool)  
  end

  def view
    if params[:sectionid] then
      @section = @expt.find_section_with_id(params[:sectionid])
      raise "Section not found" unless @section
      @section.execute(@expt.db) unless @section.executed?
    end
  end

  def show_section
    @section = @expt.find_section_with_id(params[:sectionid])
    raise "Section with id #{params[:sectionid]} not found" unless @section
    @section.execute(@expt.db) unless @section.executed?
    respond_to do |format|
      format.js { render :action => 'show_section.rjs', :locals =>{ :section => @section }}
    end
  end

  # GET /expts/new
  def new
    @expt = Expt.new
  end

  # POST /expts
  def create
    @expt = Expt.new(params[:expt])
    @expts = user_session.get_expts
    if user_session.loaded?(@expt.to_param) then
      raise "Experiment is already loaded"
    end
    @expt.load_from_disk
    user_session.save_expt(@expt)
    if params[:show] then
      redirect_to expt_url @expt and return
    end
    @expts = user_session.get_expts
    respond_to do |format|
      format.js { render :action => 'new.rjs'}
    end
  end

  def las #load and show
    load(params[:expt])
    redirect_to expt_url @expt
  end

  def lac #load and compare
    @expts = user_session.get_expts
    if params[:expts].nil? or params[:expts].length < 2
      raise "You need to select atleast two experiments to compare"
    end    
    cexpts = params[:expts].collect {|e| load({:path=>e})}
    name = "Compare_" + cexpts.collect{|e| e.name}.join("_")
    @expt = Expt.new({:path=>name})
    unless user_session.loaded?(@expt.to_param) then
      @expt.compare_loaded_databases(cexpts)
      @expt.name = name
      user_session.save_expt(@expt)
    end
    redirect_to expt_url @expt and return
  end

  # DELETE /expts/1
  def destroy
    user_session.delete_expt(params[:id])
    @expts = user_session.get_expts
    #@expt.destroy

    respond_to do |format|
      format.js { render :action => 'delete.rjs'}
    end
  end

  def image
    section = @expt.find_section_with_id(params[:sectionid])
    send_data(section.image,
      :disposition => 'inline',
      :type => 'image/png',
      :filename => section.desc.gsub(/ /,"")+".png")
  end

  def sparkline
    section = @expt.find_section_with_id(params[:sectionid])
    data = section.sparkline(params[:i].to_i, params[:j].to_i)
    send_data(data,
      :disposition => 'inline',
      :type => 'image/png',
      :filename => section.desc.gsub(/ /,"")+".png")
  end

  def new_from_compare
    @expts = user_session.get_expts
    if params[:expts].nil? or params[:expts].length < 2
      raise "You need to select atleast two experiments to compare"
    end
    cexpts = params[:expts].collect {|e| user_session.find_expt(e)}
    name = "Compare_" + cexpts.collect{|e| e.name}.join("_")
    @expt = Expt.new({:path=>name})
    if user_session.loaded?(@expt.to_param) then
      raise "Experiment #{@expt.name}is already compared"
    end
    @expt.compare_loaded_databases(cexpts)
    @expt.name = name
    user_session.save_expt(@expt)
    @expts = user_session.get_expts
    respond_to do |format|
      format.js { render :action => 'new.rjs'}
    end
  end

  def custom_query
    desc = params[:desc]
    query = params[:query]
    dims = params[:dims]
    display = params[:display]
    @section = Fenxi.new_section(["Dynamic", desc, display, dims, query])
    @section.execute(@expt.db)
    @expt.tools["Dynamic"] << @section
    respond_to do |format|
      format.js { render :action => 'show_section.rjs', :locals =>{ :section => @section }}
    end
  end
  
  private
  # Ensure the experiment is loaded
  def load(phash)
    @expt = Expt.new(phash)
    logger.warn("Loading #{phash.inspect}")
    unless user_session.loaded?(@expt.to_param) then
      @expt.load_from_disk
      user_session.save_expt(@expt)
    end
    @expt
  end

  def get_expt
    @expt = user_session.find_expt(params[:id])
    @expts = user_session.get_expts
  end
  def default_tool_for(expt)
    #first search for profile, if not return 1st tool
    tool = expt.tools.keys.find {|name| name == "profile"}
    return tool unless tool.nil?
    return expt.tools.keys.first
  end
  def respond_catch_exception_rjs
    begin
      yield
    rescue Exception => ex
      logger.warn(ex.message)
      logger.warn(ex.backtrace[0..3].join("\n"))
      respond_to do |format|
        format.js do
          @error = ex.message # FIXME: Need a better way to do this
          render :action => 'error.rjs'
        end
      end
    end
  end
end

src/rails/app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

src/rails/app/helpers/expts_helper.rb
module ExptsHelper
  def section_type(section)
    if section.exception then
      "exception"
    elsif section.class.to_s == "Fenxi::ChartSection"
      "chart"
    else
      "table"
    end
  end
  def supported_display_types
    options = [["Table", "table"]]
    Fenxi::Chart.supported_chart_types.each do |e|
      options << [e, e.downcase]
    end
    options
  end
  def pretty_tool_list(expt)
    Fenxi::FenxiUtil.pretty_tool_list(expt.tools.keys)
    #{ host => [[realname, prettyname],..] }
  end  
end

src/rails/app/views/expts/_chart.html.erb
<P>
  <%= image_tag url_for(:controller => 'expts', :action => 'image',
    :id=>@expt, :sectionid => section.id),:alt => section.desc %>
</P>

src/rails/app/views/expts/_custom_query.html.erb
<a href="#" onclick="Effect.toggle(<%="'custom-query-id-#{section.id}'"%>, 'appear');return false;">Edit</a>
<div class="custom-query" id="<%="custom-query-id-#{section.id}"%>" style="display:none;">
<% form_remote_tag :url => { :action => "custom_query" },
  :loading => 'CustomQueryExecutor.loading()',
  :complete => 'CustomQueryExecutor.complete()',
  :html => { :id => 'custom-query-form' } do
%>
  <%=  hidden_field_tag 'id', @expt.to_param %>
  <%=  hidden_field_tag 'dims', section.dims %>
  <table>
    <tr>
      <td><%= label_tag 'Title'%></td>
      <td><%= text_field_tag 'desc', section.desc, :size=>"50" %></td>
    </tr>
    <tr>
      <td><%= label_tag 'Display as' %></td>
      <td><%= select_tag 'display', options_for_select(supported_display_types, section.display) %></td>
    </tr>
    <tr>
      <td><%= label_tag 'query' %></td>
      <td><%= text_area_tag 'query', section.query, :size => "50x5" %></td>
    </tr>
    <tr>
      <td colspan="2"><%= submit_tag 'Execute custom query' %></td>
    </tr>    
  </table>
<%end%>
</div>

src/rails/app/views/expts/_exception.html.erb
<div class="exception">
  <P style="color: red; font-size:120%;">
    <%=exception.message %>
  </P>
  <PRE><%= exception.backtrace[0..2].join("\n") %></PRE>
</div>

src/rails/app/views/expts/_expt.html.erb
<tr id="expt-<%=expt.to_param%>">
  <td><%= check_box_tag "expts[]", expt.to_param %></td>
  <td><%= link_to h(expt.name), expt %></td>
  <td><%= h(expt.path)%></td>
  <td><%= link_to_remote 'Unload',:url => expt_url(:id => expt), :method => :delete%></td>
</tr>

src/rails/app/views/expts/_host_list.html.erb
<%= content_tag(:div, host, :class=>"hostname") if host != "nil" %>
<% tools.each do |tool| %>
  <div class="tool-name">
    <a href="<%= url_for(:id=>@expt.to_param, :action=>:show, :tool =>tool.first)%>" class="tool-list-href">
      <%= tool.last%><span><%=tool.first%></span></a>
  <%#= link_to tool.last, {:id=>@expt.to_param, :tool =>tool.first}, :class=>"tool-list-href" %>
  </div>
<% end %>
<%#= render :partial => 'tool_list', :collection => tools, :as => :tool %>

src/rails/app/views/expts/_section.html.erb
<div class="section" id="section-<%=section.id%>">
  <h2><%= section.desc %></h2>
  <P>
    <% type = section_type(section) %>
    <%  case
    when type == "exception" then
    %>
      <%= render :partial => 'exception', :object => section.exception %>
    <% when type == "chart" then %>
      <%= render :partial => 'chart', :locals => { :section => section } %>
    <% else %>
      <%= render :partial => 'section_table', :locals => { :section => section }%>
    <% end %>
  <div class="prevnext">
    <%- if @expt.db -%>      
      <%= render :partial => 'custom_query',:locals => { :section => section }%>
    <%- end -%>
  </div>
    </P>
</div>

src/rails/app/views/expts/_section_table.html.erb
<% rowno = 0 %>
<% if @expt.db.nil? then %>
    <div class="compare_table_funcs">
    <a href="#" onclick="color_code('table<%=section.id%>');return false;">Color code</a> |
    <a href="#" onclick="hide_similar('table<%=section.id%>');return false;">Hide similar</a> |
    <a href="#" onclick="show_all('table<%=section.id%>');return false;">Show All</a><BR>
  </div>
<%  end %>
<table class="section-table" id="table<%=section.id%>">
  <thead>
    <% section.query_result.headers.each do |header| %>
      <th><%= h(header)%></th>
    <%end%>
  </thead>
  <tbody>
    <% section.query_result.rows.each_with_index do |row, i| %>
      <tr class="row<%=rowno%>">
        <% rowno = 1 - rowno %>
        <% row.each_with_index do |col, j| %>
          <td class="<%=section.query_result.types[j] %>">
            <%
            case
            when section.query_result.types[j] == "image" %>
              <%= image_tag url_for(:controller => 'expts', :action => 'sparkline',
                :id=>@expt, :sectionid => section.id, :i => i, :j => j) %>
            <%  when section.query_result.types[j] == "float" %>
              <%=  (col == "-") ? "-" : "%.2f" % col.to_f %>
            <%  else %>
              <%= col %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

src/rails/app/views/expts/_tool.html.erb
<div class="tool-page">
  <h2><%= @tool %></h2>
  <%= render :partial => 'section', :collection=>@expt.tools[@tool], :as => :section %>
</div>

src/rails/app/views/expts/_tool_list.html.erb
<%#Input: @expt, and tool =>[realname, prettyname]%>
<div class="tool=list-box">
  <div class="tool-name">
    <a href="#" class="tool-list-href" id="tool-<%=tool.last%>"
       onclick="Effect.toggle('sections-<%=tool.first%>', 'appear',{ duration: 0.5 });return false;">
      <%= tool.last %><span><%= tool.first %></span>
    </a>
  </div>
  <div class="section-list" id="sections-<%=tool.first%>" style="display:none;">
    <div>
      <ul>
        <% @expt.sections_for_tool(tool.first).each do |section| %>
          <LI><%= link_to_remote "#{h(section.desc)}",
              :url=>url_for(:action=>"show_section", :id=>@expt, :sectionid => section.id),
              :loading => "Element.show('spinner');",
              :complete => "Element.hide('spinner');"
          %> </LI>
          <% end %>
      </ul>
    </div>
  </div>
</div>

src/rails/app/views/expts/_tool_toc.html.erb
<div class="tool-name">
  <span class="current-tool-name"><%= h(@tool) %></span>
  <div class="section-list">
    <ul class="tool-toc">
      <% @expt.tools[@tool].each do |section|  %>
        <li><%= link_to h(section.desc), "#section-#{section.id}"%></li>
      <%  end %>
    </ul>
  </div>
</div>

src/rails/app/views/expts/index.html.erb
<p style="color: red" id="ajax-error"></p>
<div id="fcontent">
  <div id="expts-list" style="<%= @expts.length > 0 ? "" : "display:none;"%>" >
    <% form_remote_tag :url => url_for(:action => "new_from_compare"),
      :loading => 'ExperimentLoader.disableExptForm()',
      :complete => 'ExperimentLoader.enableExptForm()',
      :html => { :id => 'compare-form' } do %>
      <table id="expts" class="section-table">
        <thead><tr>
            <th>&nbsp;</th>
            <th>Experiment Name</th>
            <th>Path</th>
            <th>Unload</th>
          </tr>
        </thead>
        <%= render :partial => 'expt', :collection => @expts, :as => :expt %>
      </table>
      <%= submit_tag "Compare experiments" %>
    <% end %>
  </div>
</div>
<P>
<h3>Load an experiment from disk</h3>
<P>
  <div id="expt-form-div">
    <% form_remote_for :expt,
      Expt.new,
      :url => { :action => "create" },
      :loading => 'ExperimentLoader.disableExptForm()',
      :complete => 'ExperimentLoader.enableExptForm()',
      :html => { :id => 'expt-form' } do |f| %>
      <label for="expt-path">Path:</label>
      <%= f.text_field :path, :size => 60 %>
      <%= submit_tag 'Load experiment' %>
    <% end %>
  </div>
</P>

src/rails/app/views/expts/show.html.erb
<% @page_title = "Viewing #{h(@expt.name)} -- Fenxi" %>
<h3><%= link_to 'Experiments', expts_path%> &raquo; <%= h(@expt.name) %></h3>
<table class="section-show">
  <tr valign="top">
    <td style="width:200px;">
      <!-- show current tool -->
      <%= render :partial => 'tool_toc' %>
      <% pretty_list = pretty_tool_list(@expt)
      pretty_list.each do |host, tools| %>
        <%= render :partial => 'host_list', :locals => {:host=>host, :tools=> tools} %>
      <% end %>
    </td>
    <td>
      <p style="color: red" id="ajax-error"></p>
      <div id="section-holder">
        <% if @tool then %>
          <%= render :partial => 'tool', :object => @tool%>
        <% end %>
      </div>
    </td>
  </tr>
</table>
<div id="footer">
  <%= link_to 'Back', expts_path %>
</div>

src/rails/app/views/expts/view.html.erb
<% @page_title = "Viewing #{h(@expt.name)} -- Fenxi" %>
<h3><%= link_to 'Experiments', expts_path%> &raquo; <%= h(@expt.name) %></h3>
<table class="section-show">
  <tr valign="top">
    <td style="width:200px;">
      <% pretty_list = pretty_tool_list(@expt)
      pretty_list.each do |host, tools| %>
        <%= render :partial => 'host_list', :locals => {:host=>host, :tools=> tools} %>
      <% end %>
    </td>
    <td>
      <p style="color: red" id="ajax-error"></p>
      <div id="section-holder">
        <% if @section then %>
          <%= render :partial => 'section', :object => @section%>
        <% end %>
      </div>
    </td>
  </tr>
</table>
<div id="footer">
  <%= link_to 'Back', expts_path %>
</div>

src/rails/app/views/layouts/expts.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title><%= @page_title || "Fenxi" %></title>
    <%#= stylesheet_link_tag 'scaffold' %>
    <%= javascript_include_tag :defaults %>
    <%= stylesheet_link_tag 'fenxi' %>
  </head>
  <body>
    <div class="header">
      <div class="logo">
        <span class="fenxibig">fenxi</span>
        <%= image_tag 'spinner.gif', :id => 'spinner', :style => 'display:none;' %>
      </div>
      <div id="menu">
        <ul>
          <li><%= link_to 'Experiments', expts_path %></li>
          <li><a href="http://fenxi.dev.java.net">Download</a></li>
          <li><a href="http://fenxi.dev.java.net/manual.html">Help</a></li>
        </ul>
      </div>
    </div>

    <div id="container">
      <p style="color: red" id="flash-error"><%= flash[:error] %></p>
      <p style="color: green" id="flash-notice"><%= flash[:notice] %></p>
      <%= yield %>
    </div>
  </body>
</html>